### ISSUE TITLE
License

### ISSUE THREAD

**Issue by vweevers** [pjeby/autocreate#1]
FIY, I reused a big chunk of your code (thanks!) for [replace-constructor](https://github.com/vweevers/replace-constructor).

OK to redistribute replace-constructor under MIT license?

**Comment by pjeby** [comment]
Sure.  (Although I should probably just refactor autocreate to expose the `named()` and `copyProps()` functions to begin with, or extract them to modules.)

**Comment by vweevers** [comment]
Thanks. +1 to extracting those.
